version: '3.8'
services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - report
  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: kafka-container
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka # docker-machine ip
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - "zookeeper"
    networks:
      - report
  report-api:
    image: report-api
    container_name: report-api
    ports:
      - "8081:8081"
    environment:
        KAFKA_HOST: kafka:9092
    networks:
      - report
    depends_on:
      - kafka
  report-generator:
    image: report-generator
    container_name: report-generator
    ports:
      - "8080:8080"
    environment:
      KAFKA_HOST: kafka:9092
      SMTP_PASS: your_smtp_pass
    networks:
      - report
    depends_on:
      - kafka

networks:
  report:
    driver: bridge
#  docker-compose exec kafka kafka-topics.sh --create --topic report --partitions 1 --replication-factor 1 --bootstrap-server kafka:9092