apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-api-deployment
  labels:
    deployment: report-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report-api
  template:
    metadata:
      labels:
        app: report-api
    spec:
      containers:
        - name: report-api
          image: pashonokk/report-api
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: KAFKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: kafka-configmap
                  key: kafka-host
      restartPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: report-api-service
spec:
  selector:
    app: report-api
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 32000